# bbport: link closure of a static library, for linking it outside CMake (build.sh links
# bb-probe.exe with the C driver on Windows). Writes one linker argument per line: the library
# itself, then its transitive dependencies in an order that satisfies GNU ld and lld (a library
# is listed after every library that uses it).

function(_bb_link_closure_visit item)
    if (item MATCHES "^\\$<LINK_ONLY:(.*)>$")
        set(item "${CMAKE_MATCH_1}")
    endif()
    if (item STREQUAL "" OR item MATCHES "^\\$<")
        return()
    endif()
    if (TARGET "${item}")
        get_target_property(aliased "${item}" ALIASED_TARGET)
        if (aliased)
            set(item "${aliased}")
        endif()
        get_property(on_stack GLOBAL PROPERTY _BB_LINK_STACK)
        if ("${item}" IN_LIST on_stack)
            return()
        endif()
        set_property(GLOBAL APPEND PROPERTY _BB_LINK_STACK "${item}")
        get_target_property(type "${item}" TYPE)
        get_target_property(imported "${item}" IMPORTED)
        if (type STREQUAL "SHARED_LIBRARY")
            set_property(GLOBAL APPEND PROPERTY _BB_LINK_ITEMS "$<TARGET_LINKER_FILE:${item}>")
        elseif (type STREQUAL "STATIC_LIBRARY" OR (imported AND type STREQUAL "UNKNOWN_LIBRARY"))
            set_property(GLOBAL APPEND PROPERTY _BB_LINK_ITEMS "$<TARGET_FILE:${item}>")
        endif()
        get_target_property(options "${item}" INTERFACE_LINK_OPTIONS)
        if (options)
            foreach(option IN LISTS options)
                set_property(GLOBAL APPEND PROPERTY _BB_LINK_ITEMS "${option}")
            endforeach()
        endif()
        get_target_property(deps "${item}" INTERFACE_LINK_LIBRARIES)
        if (deps)
            foreach(dep IN LISTS deps)
                _bb_link_closure_visit("${dep}")
            endforeach()
        endif()
        get_property(on_stack GLOBAL PROPERTY _BB_LINK_STACK)
        list(REMOVE_ITEM on_stack "${item}")
        set_property(GLOBAL PROPERTY _BB_LINK_STACK "${on_stack}")
    elseif (item MATCHES "^-" OR IS_ABSOLUTE "${item}")
        set_property(GLOBAL APPEND PROPERTY _BB_LINK_ITEMS "${item}")
    else()
        set_property(GLOBAL APPEND PROPERTY _BB_LINK_ITEMS "-l${item}")
    endif()
endfunction()

function(bb_write_link_closure target output)
    set_property(GLOBAL PROPERTY _BB_LINK_ITEMS "")
    set_property(GLOBAL PROPERTY _BB_LINK_STACK "")
    _bb_link_closure_visit(${target})
    get_property(items GLOBAL PROPERTY _BB_LINK_ITEMS)
    # Keep the last occurrence of each item: dependencies end up after all their users.
    list(REVERSE items)
    list(REMOVE_DUPLICATES items)
    list(REVERSE items)
    # SDL3's pkg-config adds -mwindows (GUI subsystem): bb-probe keeps its console output.
    list(REMOVE_ITEM items -mwindows)
    # The C++ runtime (the exe is linked by the C driver) and the Windows libraries the vendored
    # code calls directly; onecore last (CreateFileMapping2 and the other Windows 10 memory APIs
    # kernel32's import library lacks). CLANG64: libc++, whose threads and locks are Win32's own.
    if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(cxx_runtime -lc++)
    else()
        set(cxx_runtime -lstdc++)
    endif()
    list(APPEND items ${cxx_runtime} -lwinmm -lws2_32 -lbcrypt -lole32 -lshell32 -luser32 -lpsapi
        -lkernel32 -lonecore)
    list(JOIN items "\n" content)
    file(GENERATE OUTPUT "${output}" CONTENT "${content}\n" NEWLINE_STYLE UNIX)
endfunction()
