name: Build and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --user root

    steps:
      - name: Install git and base tools
        run: |
          pacman -Sy --noconfirm git base-devel cmake ninja python glslang sdl3 vulkan-headers vulkan-icd-loader zydis xbyak

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          bash build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bbport-linux-build
          path: |
            out/
            run.sh
            build.sh
            launcher/
