#pragma once

#include <cstddef>

namespace BbStrings {

enum class StringId : int {
    WindowTitle = 0,
    FpsMs,
    SectionLanguage,
    LanguageInterface,
    SectionUpscaler,
    UpscalerCombo,
    UpscalerOff,
    UpscalerTaa,
    UpscalerNotSupported,
    UpscalerWorkInProgress,
    Fsr4Unavailable,
    Fsr4ActiveModeSelected,
    HintFsr411,
    HintFsr411Fp8,
    HintFsr4,
    Fsr4AutoExposure,
    Fsr4InvertJitter,
    HintFsr4Ghosting,
    PresetCombo,
    PresetRenderWord,
    HintTaa,
    ActiveSceneRender,
    StartupPreset,
    HintRenderResAuto,
    HintRenderResManual,
    HintRenderResLive,
    SharpeningRcas,
    SharpnessIntensity,
    HintSharpness,
    SubpixelJitter,
    HintJitter,
    SectionReactivity,
    ReactivityEnable,
    HintReactivity,
    ReactivityScale,
    ReactivityThreshold,
    ReactivityMax,
    ReactivityShowMask,
    ObjectMotionVectors,
    HintObjectMotion,
    ObjectMotionShowDebug,
    HintObjectMotionColors,
    SectionOutputResolution,
    OutputResolutionCombo,
    HintOutputResolutionFixed,
    HintOutputResolutionLive,
    DynamicResolutionChange,
    LiveModeAuto,
    LiveModeDisabled,
    LiveModeEnabled,
    HintLiveResolution,
    SectionGameEffects,
    LodCombo,
    LodMax,
    LodDefault,
    LodLower,
    LodMin,
    HintGameEffects,
    HintSpecialControls,
    RestartWarning,
    ApplyAndRestart,
    SectionMisc,
    ShowFpsCorner,
    PuddleReflections,
    HintPuddleReflections,
    DrawPipe,
    HintDrawPipe,
    DrawPipeModeOff,
    DrawPipeModeOn,
    DrawPipeModeHybrid,
    CloseButton,
    SavedToIni,
    PromptKeyboardHelp,
    KbSpace,
    KbBackspace,
    KbClear,
    KbConfirm,
    KbCancel,
    KbCaps,
    PromptGamepadHelp,
    SectionFrameGeneration,
    FrameGenerationEnable,
    HintFrameGeneration,
    FrameGenerationNotSupported,
    Count
};

/// Returns the localized string for the specified ID and language (0 = EN, 1 = PT-BR, 2 = RU).
const char* Get(StringId id, int lang);

/// Returns the localized label for a game effect index (0..9).
const char* EffectLabel(int effect_index, int lang);

} // namespace BbStrings
